return {
	["US"] = { Name = "United States", Emoji = "🇺🇸" },
	["UK"] = { Name = "United Kingdom", Emoji = "🇬🇧" },
	["CA"] = { Name = "Canada", Emoji = "🇨🇦" },
	["AF"] = { Name = "Afghanistan", Emoji = "🇦🇫" },
	["AX"] = { Name = "Aland Islands", Emoji = "🇦🇽" },
	["AL"] = { Name = "Albania", Emoji = "🇦🇱" },
	["DZ"] = { Name = "Algeria", Emoji = "🇩🇿" },
	["AS"] = { Name = "American Samoa", Emoji = "🇦🇸" },
	["AD"] = { Name = "Andorra", Emoji = "🇦🇩" },
	["AO"] = { Name = "Angola", Emoji = "🇦🇴" },
	["AI"] = { Name = "Anguilla", Emoji = "🇦🇮" },
	["AQ"] = { Name = "Antarctica", Emoji = "🇦🇶" },
	["AG"] = { Name = "Antigua and Barbuda", Emoji = "🇦🇬" },
	["AR"] = { Name = "Argentina", Emoji = "🇦🇷" },
	["AM"] = { Name = "Armenia", Emoji = "🇦🇲" },
	["AW"] = { Name = "Aruba", Emoji = "🇦🇼" },
	["AU"] = { Name = "Australia", Emoji = "🇦🇺" },
	["AT"] = { Name = "Austria", Emoji = "🇦🇹" },
	["AZ"] = { Name = "Azerbaijan", Emoji = "🇦🇿" },
	["BS"] = { Name = "Bahamas", Emoji = "🇧🇸" },
	["BH"] = { Name = "Bahrain", Emoji = "🇧🇭" },
	["BD"] = { Name = "Bangladesh", Emoji = "🇧🇩" },
	["BB"] = { Name = "Barbados", Emoji = "🇧🇧" },
	["BY"] = { Name = "Belarus", Emoji = "🇧🇾" },
	["BE"] = { Name = "Belgium", Emoji = "🇧🇪" },
	["BZ"] = { Name = "Belize", Emoji = "🇧🇿" },
	["BJ"] = { Name = "Benin", Emoji = "🇧🇯" },
	["BM"] = { Name = "Bermuda", Emoji = "🇧🇲" },
	["BT"] = { Name = "Bhutan", Emoji = "🇧🇹" },
	["BO"] = { Name = "Bolivia", Emoji = "🇧🇴" },
	["BQ"] = { Name = "Bonaire, Saint Eustatius and Saba", Emoji = "🇧🇶" },
	["BA"] = { Name = "Bosnia and Herzegovina", Emoji = "🇧🇦" },
	["BW"] = { Name = "Botswana", Emoji = "🇧🇼" },
	["BV"] = { Name = "Bouvet Island", Emoji = "🇧🇻" },
	["BR"] = { Name = "Brazil", Emoji = "🇧🇷" },
	["IO"] = { Name = "British Indian Ocean Territory", Emoji = "🇮🇴" },
	["BN"] = { Name = "Brunei Darussalam", Emoji = "🇧🇳" },
	["BG"] = { Name = "Bulgaria", Emoji = "🇧🇬" },
	["BF"] = { Name = "Burkina Faso", Emoji = "🇧🇫" },
	["BI"] = { Name = "Burundi", Emoji = "🇧🇮" },
	["KH"] = { Name = "Cambodia", Emoji = "🇰🇭" },
	["CM"] = { Name = "Cameroon", Emoji = "🇨🇲" },
	["CV"] = { Name = "Cape Verde", Emoji = "🇨🇻" },
	["KY"] = { Name = "Cayman Islands", Emoji = "🇰🇾" },
	["CF"] = { Name = "Central African Republic", Emoji = "🇨🇫" },
	["TD"] = { Name = "Chad", Emoji = "🇹🇩" },
	["CL"] = { Name = "Chile", Emoji = "🇨🇱" },
	["CN"] = { Name = "China", Emoji = "🇨🇳" },
	["CX"] = { Name = "Christmas Island", Emoji = "🇨🇽" },
	["CC"] = { Name = "Cocos Islands", Emoji = "🇨🇨" },
	["CO"] = { Name = "Colombia", Emoji = "🇨🇴" },
	["KM"] = { Name = "Comoros", Emoji = "🇰🇲" },
	["CG"] = { Name = "Congo", Emoji = "🇨🇬" },
	["CD"] = { Name = "Congo (DRC)", Emoji = "🇨🇩" },
	["CK"] = { Name = "Cook Islands", Emoji = "🇨🇰" },
	["CR"] = { Name = "Costa Rica", Emoji = "🇨🇷" },
	["CI"] = { Name = "Ivory Coast", Emoji = "🇨🇮" },
	["HR"] = { Name = "Croatia", Emoji = "🇭🇷" },
	["CW"] = { Name = "Curaçao", Emoji = "🇨🇼" },
	["CY"] = { Name = "Cyprus", Emoji = "🇨🇾" },
	["CZ"] = { Name = "Czech Republic", Emoji = "🇨🇿" },
	["DK"] = { Name = "Denmark", Emoji = "🇩🇰" },
	["DJ"] = { Name = "Djibouti", Emoji = "🇩🇯" },
	["DM"] = { Name = "Dominica", Emoji = "🇩🇲" },
	["DO"] = { Name = "Dominican Republic", Emoji = "🇩🇴" },
	["EC"] = { Name = "Ecuador", Emoji = "🇪🇨" },
	["EG"] = { Name = "Egypt", Emoji = "🇪🇬" },
	["SV"] = { Name = "El Salvador", Emoji = "🇸🇻" },
	["GQ"] = { Name = "Equatorial Guinea", Emoji = "🇬🇶" },
	["ER"] = { Name = "Eritrea", Emoji = "🇪🇷" },
	["EE"] = { Name = "Estonia", Emoji = "🇪🇪" },
	["ET"] = { Name = "Ethiopia", Emoji = "🇪🇹" },
	["FK"] = { Name = "Falkland Islands (Malvinas)", Emoji = "🇫🇰" },
	["FO"] = { Name = "Faroe Islands", Emoji = "🇫🇴" },
	["FJ"] = { Name = "Fiji", Emoji = "🇫🇯" },
	["FI"] = { Name = "Finland", Emoji = "🇫🇮" },
	["FR"] = { Name = "France", Emoji = "🇫🇷" },
	["GF"] = { Name = "French Guiana", Emoji = "🇬🇫" },
	["PF"] = { Name = "French Polynesia", Emoji = "🇵🇫" },
	["TF"] = { Name = "French Southern Territories", Emoji = "🇹🇫" },
	["GA"] = { Name = "Gabon", Emoji = "🇬🇦" },
	["GM"] = { Name = "Gambia", Emoji = "🇬🇲" },
	["GE"] = { Name = "Georgia", Emoji = "🇬🇪" },
	["DE"] = { Name = "Germany", Emoji = "🇩🇪" },
	["GH"] = { Name = "Ghana", Emoji = "🇬🇭" },
	["GI"] = { Name = "Gibraltar", Emoji = "🇬🇮" },
	["GR"] = { Name = "Greece", Emoji = "🇬🇷" },
	["GL"] = { Name = "Greenland", Emoji = "🇬🇱" },
	["GD"] = { Name = "Grenada", Emoji = "🇬🇩" },
	["GP"] = { Name = "Guadeloupe", Emoji = "🇬🇵" },
	["GU"] = { Name = "Guam", Emoji = "🇬🇺" },
	["GT"] = { Name = "Guatemala", Emoji = "🇬🇹" },
	["GG"] = { Name = "Guernsey", Emoji = "🇬🇬" },
	["GN"] = { Name = "Guinea", Emoji = "🇬🇳" },
	["GW"] = { Name = "Guinea-Bissau", Emoji = "🇬🇼" },
	["GY"] = { Name = "Guyana", Emoji = "🇬🇾" },
	["HT"] = { Name = "Haiti", Emoji = "🇭🇹" },
	["HM"] = { Name = "Heard Island and the McDonald Islands", Emoji = "🇭🇲" },
	["VA"] = { Name = "Holy See", Emoji = "🇻🇦" },
	["HN"] = { Name = "Honduras", Emoji = "🇭🇳" },
	["HK"] = { Name = "Hong Kong", Emoji = "🇭🇰" },
	["HU"] = { Name = "Hungary", Emoji = "🇭🇺" },
	["IS"] = { Name = "Iceland", Emoji = "🇮🇸" },
	["IN"] = { Name = "India", Emoji = "🇮🇳" },
	["ID"] = { Name = "Indonesia", Emoji = "🇮🇩" },
	["IQ"] = { Name = "Iraq", Emoji = "🇮🇶" },
	["IE"] = { Name = "Ireland", Emoji = "🇮🇪" },
	["IM"] = { Name = "Isle of Man", Emoji = "🇮🇲" },
	["IL"] = { Name = "Israel", Emoji = "🇮🇱" },
	["IT"] = { Name = "Italy", Emoji = "🇮🇹" },
	["JM"] = { Name = "Jamaica", Emoji = "🇯🇲" },
	["JP"] = { Name = "Japan", Emoji = "🇯🇵" },
	["JE"] = { Name = "Jersey", Emoji = "🇯🇪" },
	["JO"] = { Name = "Jordan", Emoji = "🇯🇴" },
	["KZ"] = { Name = "Kazakhstan", Emoji = "🇰🇿" },
	["KE"] = { Name = "Kenya", Emoji = "🇰🇪" },
	["KI"] = { Name = "Kiribati", Emoji = "🇰🇮" },
	["KR"] = { Name = "Korea", Emoji = "🇰🇷" },
	["KW"] = { Name = "Kuwait", Emoji = "🇰🇼" },
	["KG"] = { Name = "Kyrgyzstan", Emoji = "🇰🇬" },
	["LA"] = { Name = "Laos", Emoji = "🇱🇦" },
	["LV"] = { Name = "Latvia", Emoji = "🇱🇻" },
	["LB"] = { Name = "Lebanon", Emoji = "🇱🇧" },
	["LS"] = { Name = "Lesotho", Emoji = "🇱🇸" },
	["LR"] = { Name = "Liberia", Emoji = "🇱🇷" },
	["LY"] = { Name = "Libya", Emoji = "🇱🇾" },
	["LI"] = { Name = "Liechtenstein", Emoji = "🇱🇮" },
	["LT"] = { Name = "Lithuania", Emoji = "🇱🇹" },
	["LU"] = { Name = "Luxembourg", Emoji = "🇱🇺" },
	["MO"] = { Name = "Macao", Emoji = "🇲🇴" },
	["MK"] = { Name = "Macedonia", Emoji = "🇲🇰" },
	["MG"] = { Name = "Madagascar", Emoji = "🇲🇬" },
	["MW"] = { Name = "Malawi", Emoji = "🇲🇼" },
	["MY"] = { Name = "Malaysia", Emoji = "🇲🇾" },
	["MV"] = { Name = "Maldives", Emoji = "🇲🇻" },
	["ML"] = { Name = "Mali", Emoji = "🇲🇱" },
	["MT"] = { Name = "Malta", Emoji = "🇲🇹" },
	["MH"] = { Name = "Marshall Islands", Emoji = "🇲🇭" },
	["MQ"] = { Name = "Martinique", Emoji = "🇲🇶" },
	["MR"] = { Name = "Mauritania", Emoji = "🇲🇷" },
	["MU"] = { Name = "Mauritius", Emoji = "🇲🇺" },
	["YT"] = { Name = "Mayotte", Emoji = "🇾🇹" },
	["MX"] = { Name = "Mexico", Emoji = "🇲🇽" },
	["FM"] = { Name = "Micronesia", Emoji = "🇫🇲" },
	["MD"] = { Name = "Moldova", Emoji = "🇲🇩" },
	["MC"] = { Name = "Monaco", Emoji = "🇲🇨" },
	["MN"] = { Name = "Mongolia", Emoji = "🇲🇳" },
	["ME"] = { Name = "Montenegro", Emoji = "🇲🇪" },
	["MS"] = { Name = "Montserrat", Emoji = "🇲🇸" },
	["MA"] = { Name = "Morocco", Emoji = "🇲🇦" },
	["MZ"] = { Name = "Mozambique", Emoji = "🇲🇿" },
	["MM"] = { Name = "Myanmar", Emoji = "🇲🇲" },
	["NA"] = { Name = "Namibia", Emoji = "🇳🇦" },
	["NR"] = { Name = "Nauru", Emoji = "🇳🇷" },
	["NP"] = { Name = "Nepal", Emoji = "🇳🇵" },
	["NL"] = { Name = "Netherlands", Emoji = "🇳🇱" },
	["AN"] = { Name = "Netherlands Antilles", Emoji = "🇳🇱" },
	["NC"] = { Name = "New Caledonia", Emoji = "🇳🇨" },
	["NZ"] = { Name = "New Zealand", Emoji = "🇳🇿" },
	["NI"] = { Name = "Nicaragua", Emoji = "🇳🇮" },
	["NE"] = { Name = "Niger", Emoji = "🇳🇪" },
	["NG"] = { Name = "Nigeria", Emoji = "🇳🇬" },
	["NU"] = { Name = "Niue", Emoji = "🇳🇺" },
	["NF"] = { Name = "Norfolk Island", Emoji = "🇳🇫" },
	["MP"] = { Name = "Northern Mariana Islands", Emoji = "🇲🇵" },
	["NO"] = { Name = "Norway", Emoji = "🇳🇴" },
	["OM"] = { Name = "Oman", Emoji = "🇴🇲" },
	["PK"] = { Name = "Pakistan", Emoji = "🇵🇰" },
	["PW"] = { Name = "Palau", Emoji = "🇵🇼" },
	["PS"] = { Name = "Palestine", Emoji = "🇵🇸" },
	["PA"] = { Name = "Panama", Emoji = "🇵🇦" },
	["PG"] = { Name = "Papua New Guinea", Emoji = "🇵🇬" },
	["PY"] = { Name = "Paraguay", Emoji = "🇵🇾" },
	["PE"] = { Name = "Peru", Emoji = "🇵🇪" },
	["PH"] = { Name = "Philippines", Emoji = "🇵🇭" },
	["PN"] = { Name = "Pitcairn Islands", Emoji = "🇵🇳" },
	["PL"] = { Name = "Poland", Emoji = "🇵🇱" },
	["PT"] = { Name = "Portugal", Emoji = "🇵🇹" },
	["PR"] = { Name = "Puerto Rico", Emoji = "🇵🇷" },
	["QA"] = { Name = "Qatar", Emoji = "🇶🇦" },
	["RE"] = { Name = "Reunion", Emoji = "🇷🇪" },
	["RO"] = { Name = "Romania", Emoji = "🇷🇴" },
	["RU"] = { Name = "Russian Federation", Emoji = "🇷🇺" },
	["RW"] = { Name = "Rwanda", Emoji = "🇷🇼" },
	["BL"] = { Name = "Saint Barthelemy", Emoji = "🇧🇱" },
	["SH"] = { Name = "Saint Helena, Ascension and Tristan da Cunha", Emoji = "🇸🇭" },
	["KN"] = { Name = "Saint Kitts and Nevis", Emoji = "🇰🇳" },
	["LC"] = { Name = "Saint Lucia", Emoji = "🇱🇨" },
	["MF"] = { Name = "Saint Martin", Emoji = "🇲🇫" },
	["PM"] = { Name = "Saint Pierre and Miquelon", Emoji = "🇵🇲" },
	["VC"] = { Name = "Saint Vincent and the Grenadines", Emoji = "🇻🇨" },
	["WS"] = { Name = "Samoa", Emoji = "🇼🇸" },
	["SM"] = { Name = "San Marino", Emoji = "🇸🇲" },
	["ST"] = { Name = "Sao Tome and Principe", Emoji = "🇸🇹" },
	["SA"] = { Name = "Saudi Arabia", Emoji = "🇸🇦" },
	["SN"] = { Name = "Senegal", Emoji = "🇸🇳" },
	["RS"] = { Name = "Serbia", Emoji = "🇷🇸" },
	["SC"] = { Name = "Seychelles", Emoji = "🇸🇨" },
	["SL"] = { Name = "Sierra Leone", Emoji = "🇸🇱" },
	["SG"] = { Name = "Singapore", Emoji = "🇸🇬" },
	["SX"] = { Name = "Sint Maarten", Emoji = "🇸🇽" },
	["SK"] = { Name = "Slovakia", Emoji = "🇸🇰" },
	["SI"] = { Name = "Slovenia", Emoji = "🇸🇮" },
	["SB"] = { Name = "Solomon Islands", Emoji = "🇸🇧" },
	["SO"] = { Name = "Somalia", Emoji = "🇸🇴" },
	["ZA"] = { Name = "South Africa", Emoji = "🇿🇦" },
	["GS"] = { Name = "South Georgia and the South Sandwich Islands", Emoji = "🇬🇸" },
	["SS"] = { Name = "South Sudan", Emoji = "🇸🇸" },
	["ES"] = { Name = "Spain", Emoji = "🇪🇸" },
	["LK"] = { Name = "Sri Lanka", Emoji = "🇱🇰" },
	["SR"] = { Name = "Suriname", Emoji = "🇸🇷" },
	["SJ"] = { Name = "Svalbard and Jan Mayen", Emoji = "🇸🇯" },
	["SZ"] = { Name = "Swaziland", Emoji = "🇸🇿" },
	["SE"] = { Name = "Sweden", Emoji = "🇸🇪" },
	["CH"] = { Name = "Switzerland", Emoji = "🇨🇭" },
	["TW"] = { Name = "Taiwan", Emoji = "🇹🇼" },
	["TJ"] = { Name = "Tajikistan", Emoji = "🇹🇯" },
	["TZ"] = { Name = "Tanzania", Emoji = "🇹🇿" },
	["TH"] = { Name = "Thailand", Emoji = "🇹🇭" },
	["TL"] = { Name = "Timor-leste", Emoji = "🇹🇱" },
	["TG"] = { Name = "Togo", Emoji = "🇹🇬" },
	["TK"] = { Name = "Tokelau", Emoji = "🇹🇰" },
	["TO"] = { Name = "Tonga", Emoji = "🇹🇴" },
	["TT"] = { Name = "Trinidad and Tobago", Emoji = "🇹🇹" },
	["TN"] = { Name = "Tunisia", Emoji = "🇹🇳" },
	["TR"] = { Name = "Turkey", Emoji = "🇹🇷" },
	["TM"] = { Name = "Turkmenistan", Emoji = "🇹🇲" },
	["TC"] = { Name = "Turks and Caicos Islands", Emoji = "🇹🇨" },
	["TV"] = { Name = "Tuvalu", Emoji = "🇹🇻" },
	["UG"] = { Name = "Uganda", Emoji = "🇺🇬" },
	["UA"] = { Name = "Ukraine", Emoji = "🇺🇦" },
	["AE"] = { Name = "United Arab Emirates", Emoji = "🇦🇪" },
	["UM"] = { Name = "United States Minor Outlying Islands", Emoji = "🇺🇲" },
	["UY"] = { Name = "Uruguay", Emoji = "🇺🇾" },
	["UZ"] = { Name = "Uzbekistan", Emoji = "🇺🇿" },
	["VU"] = { Name = "Vanuatu", Emoji = "🇻🇺" },
	["VE"] = { Name = "Venezuela", Emoji = "🇻🇪" },
	["VN"] = { Name = "Vietnam", Emoji = "🇻🇳" },
	["VG"] = { Name = "Virgin Islands (British)", Emoji = "🇻🇬" },
	["VI"] = { Name = "Virgin Islands (US)", Emoji = "🇻🇮" },
	["WF"] = { Name = "Wallis and Futuna", Emoji = "🇼🇫" },
	["EH"] = { Name = "Western Sahara", Emoji = "🇪🇭" },
	["YE"] = { Name = "Yemen", Emoji = "🇾🇪" },
	["ZM"] = { Name = "Zambia", Emoji = "🇿🇲" },
	["ZW"] = { Name = "Zimbabwe", Emoji = "🇿🇼" },
	["CU"] = { Name = "Cuba", Emoji = "🇨🇺" },
	["IR"] = { Name = "Iran", Emoji = "🇮🇷" },
	["SY"] = { Name = "Syria", Emoji = "🇸🇾" },
	["KP"] = { Name = "North Korea", Emoji = "🇰🇵" },
}
